In [1]:
import pandas as pd

# carregando datasets

import pandas as pd

# carregando datasets

clientes = pd.read_csv("../data/raw/olist_customers_dataset.csv")
pedidos = pd.read_csv("../data/raw/olist_orders_dataset.csv")
itens_do_pedido = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
pagamentos = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
avaliações = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
produtos = pd.read_csv("../data/raw/olist_products_dataset.csv")
vendedores = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
geolocalização = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
categoria_produto = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [2]:
clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [3]:
def traduzir_cabecalhos(df):
    """
    Traduz automaticamente os cabeçalhos dos DataFrames do dataset Olist.
    """

    traducoes = {
        # Customers
        "customer_id": "id_cliente",
        "customer_unique_id": "id_unico_cliente",
        "customer_zip_code_prefix": "prefixo_cep_cliente",
        "customer_city": "cidade_cliente",
        "customer_state": "estado_cliente",

        # Orders
        "order_id": "id_pedido",
        "order_status": "status_pedido",
        "order_purchase_timestamp": "data_compra_pedido",
        "order_approved_at": "data_aprovacao_pedido",
        "order_delivered_carrier_date": "data_envio_transportadora",
        "order_delivered_customer_date": "data_entrega_cliente",
        "order_estimated_delivery_date": "data_estimada_entrega",

        # Order Items
        "order_item_id": "id_item_pedido",
        "product_id": "id_produto",
        "seller_id": "id_vendedor",
        "shipping_limit_date": "data_limite_envio",
        "price": "preco",
        "freight_value": "valor_frete",

        # Payments
        "payment_sequential": "pagamento_sequencial",
        "payment_type": "tipo_pagamento",
        "payment_installments": "quantidade_parcelas",
        "payment_value": "valor_pagamento",

        # Reviews
        "review_id": "id_avaliacao",
        "review_score": "nota_avaliacao",
        "review_comment_title": "titulo_comentario",
        "review_comment_message": "mensagem_comentario",
        "review_creation_date": "data_criacao_avaliacao",
        "review_answer_timestamp": "data_resposta_avaliacao",

        # Products
        "product_category_name": "nome_categoria_produto",
        "product_name_lenght": "tamanho_nome_produto",
        "product_description_lenght": "tamanho_descricao_produto",
        "product_photos_qty": "quantidade_fotos_produto",
        "product_weight_g": "peso_produto_g",
        "product_length_cm": "comprimento_produto_cm",
        "product_height_cm": "altura_produto_cm",
        "product_width_cm": "largura_produto_cm",

        # Geolocation
        "geolocation_zip_code_prefix": "prefixo_cep_geolocalizacao",
        "geolocation_lat": "latitude",
        "geolocation_lng": "longitude",
        "geolocation_city": "cidade_geolocalizacao",
        "geolocation_state": "estado_geolocalizacao",

        # Sellers
        "seller_zip_code_prefix": "prefixo_cep_vendedor",
        "seller_city": "cidade_vendedor",
        "seller_state": "estado_vendedor",

        # Product Category Translation
        "product_category_name_english": "nome_categoria_produto_ingles"
    }

    df = df.rename(columns=traducoes)

    return df

In [4]:
customers.columns

NameError: name 'customers' is not defined

In [ ]:
clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [ ]:
clientes.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [ ]:
produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [ ]:
produtos.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
pedidos.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00